version: '2.4'

services:

  sonarr:
    image: stlouisn/sonarr
    container_name: sonarr
    hostname: sonarr
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/sonarr/config:/config
      - /media/downloads:/downloads
      - /media/tvshows:/tv
    ports:
      - 8989
